# Generated by Django 2.1.5 on 2019-03-06 04:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name=django.contrib.auth.models.User)),
                ('password', models.TextField()),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
