# Generated by Django 2.1.5 on 2019-03-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_sys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_sys',
            old_name='user',
            new_name='username',
        ),
    ]
